"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-23 22:09:47.093196

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.database.base


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=256), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_allowed', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('max_accounts', sa.Integer(), nullable=True),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('tg_user_id', sa.BigInteger(), nullable=False),
    sa.Column('tg_username', sa.String(length=64), nullable=True),
    sa.Column('tg_first_name', sa.String(length=128), nullable=False),
    sa.Column('session_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'auth_error', 'spam_limited', 'disabled', name='accountstatus', native_enum=False, length=24), nullable=False),
    sa.Column('auto_message_enabled', sa.Boolean(), nullable=False),
    sa.Column('dm_auto_reply_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_accounts_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_accounts_owner_id_name')),
    sa.UniqueConstraint('tg_user_id', name=op.f('uq_accounts_tg_user_id'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)

    op.create_table('auto_message_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.Enum('text', 'photo', 'forward', name='contenttype', native_enum=False, length=24), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('source_peer', sa.String(length=128), nullable=True),
    sa.Column('source_msg_id', sa.Integer(), nullable=True),
    sa.Column('source_link', sa.String(length=256), nullable=True),
    sa.Column('hide_forward_source', sa.Boolean(), nullable=False),
    sa.Column('contact_enabled', sa.Boolean(), nullable=False),
    sa.Column('contact_phone', sa.String(length=32), nullable=True),
    sa.Column('contact_first_name', sa.String(length=128), nullable=True),
    sa.Column('contact_last_name', sa.String(length=128), nullable=True),
    sa.Column('text_fallback_on_media_forbidden', sa.Boolean(), nullable=False),
    sa.Column('include_archived', sa.Boolean(), nullable=False),
    sa.Column('batch_size', sa.Integer(), nullable=False),
    sa.Column('min_delay_sec', sa.Float(), nullable=False),
    sa.Column('max_delay_sec', sa.Float(), nullable=False),
    sa.Column('cycle_minutes', sa.Integer(), nullable=False),
    sa.Column('last_cycle_started_at', app.database.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_cycle_finished_at', app.database.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_cycle_at', app.database.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_cycle_targets', sa.Integer(), nullable=False),
    sa.Column('last_cycle_sent', sa.Integer(), nullable=False),
    sa.Column('last_cycle_failed', sa.Integer(), nullable=False),
    sa.Column('last_cycle_skipped', sa.Integer(), nullable=False),
    sa.Column('total_sent', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_auto_message_configs_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auto_message_configs')),
    sa.UniqueConstraint('account_id', name=op.f('uq_auto_message_configs_account_id'))
    )
    op.create_table('dm_auto_reply_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('skip_contacts', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_dm_auto_reply_configs_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dm_auto_reply_configs')),
    sa.UniqueConstraint('account_id', name=op.f('uq_dm_auto_reply_configs_account_id'))
    )
    op.create_table('dm_replied_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('peer_id', sa.BigInteger(), nullable=False),
    sa.Column('replied', sa.Boolean(), nullable=False),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_dm_replied_users_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_dm_replied_users')),
    sa.UniqueConstraint('account_id', 'peer_id', name=op.f('uq_dm_replied_users_account_id_peer_id'))
    )
    with op.batch_alter_table('dm_replied_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dm_replied_users_account_id'), ['account_id'], unique=False)

    op.create_table('exception_chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_exception_chats_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exception_chats')),
    sa.UniqueConstraint('account_id', 'chat_id', name=op.f('uq_exception_chats_account_id_chat_id'))
    )
    with op.batch_alter_table('exception_chats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exception_chats_account_id'), ['account_id'], unique=False)

    op.create_table('reply_filters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('match_type', sa.Enum('contains', 'exact', 'word', name='matchtype', native_enum=False, length=24), nullable=False),
    sa.Column('reply_text', sa.Text(), nullable=False),
    sa.Column('reply_entities', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('cooldown_sec', sa.Integer(), nullable=False),
    sa.Column('created_at', app.database.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_reply_filters_account_id_accounts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reply_filters'))
    )
    with op.batch_alter_table('reply_filters', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reply_filters_account_id'), ['account_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reply_filters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reply_filters_account_id'))

    op.drop_table('reply_filters')
    with op.batch_alter_table('exception_chats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exception_chats_account_id'))

    op.drop_table('exception_chats')
    with op.batch_alter_table('dm_replied_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dm_replied_users_account_id'))

    op.drop_table('dm_replied_users')
    op.drop_table('dm_auto_reply_configs')
    op.drop_table('auto_message_configs')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))

    op.drop_table('accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
