"""dm reply mode and whatsapp button

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-24 00:37:12.064468

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import app.database.base


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: str | None = '0001'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm_auto_reply_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_file_id', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('reply_mode', sa.Enum('first', 'always', name='dmreplymode', native_enum=False, length=24), server_default='first', nullable=False))
        batch_op.add_column(sa.Column('repeat_cooldown_min', sa.Integer(), server_default='5', nullable=False))
        batch_op.add_column(sa.Column('whatsapp_phone', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_button_text', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('whatsapp_message', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dm_auto_reply_configs', schema=None) as batch_op:
        batch_op.drop_column('whatsapp_message')
        batch_op.drop_column('whatsapp_button_text')
        batch_op.drop_column('whatsapp_phone')
        batch_op.drop_column('repeat_cooldown_min')
        batch_op.drop_column('reply_mode')
        batch_op.drop_column('photo_file_id')

    # ### end Alembic commands ###
